### ISSUE TITLE
Joomla extension PWA

### ISSUE THREAD

**Issue by jaelimaja** [tbela99/gzip#10]
Hello Mr Bela,
First up, thanks for the Gzip extension. I had used it prior, and it worked. Secondly, I'm not a developer.
I've tried Gzip now on another https site, twice, last week and today, and both times, I was thrown and locked out of my Admin back-end. The only changes I've made since, was to install security (SecurityCheck) and also backup (EJB).
Could this be the reason why Gzip is throwing me out, giving a blank page, and locking me out?
Or are there other possible reason?
Thanks
Jacquelene

**Comment by asiby** [comment]
Hello Jacquelene

Do you have access to the server's logs? Those give you an error that can help nail down the WSOD (White Screen Of Death) issues.

**Comment by jaelimaja** [comment]
Hi,
Thanks for responding. Sorry, I am just replying now. I figured out it had
to do with the secret key hiding the administrative backend.
I 'solved' it, by disabling it before I configured Gzip, and enabling it
after I've closed Gzip.
Thanks again for this extension.

Jacquelene
