### ISSUE TITLE
serviceworker.js is empty

### ISSUE THREAD

**Issue by lechoslaw** [tbela99/gzip#102]
Hi
After I enable the service worker process in plugin and load these JS files into my browser, the contents of the serviceworker.js is empty. I think the problem is due to the content of the files in the plugin package: serviceworker.js and serviceworker.min.js (in directory: /worker/dist)  are empty.

**Comment by tbela99** [comment]
Hi, not sure why they are empty but I am fixing it.

Thank you

**Comment by tbela99** [comment]
fixed
