### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode 

### ISSUE THREAD

**Issue by lechoslaw** [tbela99/gzip#104]
This problem occurs in the lighthouse on chrome.
It can be solved by: https://github.com/meanbee/magento-meanbee-pwa/issues/20  or https://stackoverflow.com/questions/48463483/what-causes-a-failed-to-execute-fetch-on-serviceworkerglobalscope-only-if

**Comment by tbela99** [comment]
Can you give more details about this issue?

thanks

**Comment by tbela99** [comment]
it looks like this is happening in a chrome extension https://bugs.chromium.org/p/chromium/issues/detail?id=823392

**Comment by tbela99** [comment]
maybe the fix is simple.
