### ISSUE TITLE
Parse Inline CSS Attribute

### ISSUE THREAD

**Issue by tbela99** [tbela99/gzip#105]
parse html style attribute and apply the same optimizations as the css files

**Comment by cbahiana** [comment]
I'm not sure if this belongs here or if I should have opened another issue, but enabling the "Parse Inline CSS Attribute" on GZIP 2.9.2 throws an error:

Notice: Undefined index: style in /home/customer/www/pwa.sd.eti.br/public_html/plugins/system/gzip/helpers/CSS.php on line 173

The error goes away disabling this option.
