### ISSUE TITLE
PWA, LightHouse error -> The start_url did respond, but not via a service worker.

### ISSUE THREAD

**Issue by lechoslaw** [tbela99/gzip#113]
Hi
I configured progressive web application settings:
- enable service worker
- enable offline HTML page
- build manifest file

I configured service worker:
- Default Network Strategy & HTML Documents: Network and Cache Fallback
- Images & JS & CSS & Fonts: Cache and Network Update

And when I run Lighthouse 6.4.0 on Chrome Canary, I got:
- "start_url does not respond with a 200 when offline The start_url did respond, but not via a service worker."
- "Manifest doesn't have a maskable icon"

Best regards

**Comment by lechoslaw** [comment]
When I enabled 'preserve log' on Console and start Lighthouse, I got errors on console: "asset-manifest.json  error 404"

**Comment by tbela99** [comment]
Thanks for the precision.

I don't remember to use 'asset-manifest.json' as a name in the source code.

I will investigate this as soon as I can

**Comment by lechoslaw** [comment]
Thank you

pon., 12 paź 2020 o 14:33 Thierry Bela Nanga <notifications@github.com>
napisał(a):
