### ISSUE TITLE
Can not install v gzip-2.9.0

### ISSUE THREAD

**Issue by ssnobben** [tbela99/gzip#119]
Hi Thierry 

trying again after some years and I really try to use this plg and install on a Joomla 3.9.24 but get this error, cant install the plugin:

**Warning**
JInstaller: :Install: File does not exist /home/site/tmp/install_6020f005a4a47/gzip-2.9.0/js/lib
**Plugin Install: Could not copy files from the source.**

**Error**
Error installing plugin
GZIP - Optimize page loading

What To Do ?

**Statistics site**
OS Linux p
PHP 7.4.14
MySQLi 10.3.27-MariaDB-log-cll-lve
Caching Enabled
Gzip Enabled
https://www.whattodo.com

**Comment by tbela99** [comment]
Sorry, I will fix it today. That folder is not used. I excluded it from the archive, but I forgot to remove the reference in the installer XML

**Comment by tbela99** [comment]
I have fixed the issue but I cannot upload the JED link right now. file upload seems broken at this time

**Comment by ssnobben** [comment]
HI thanks for fixing. I can now install it :) I have many optimisation plg so will see and test how it work together. 

Maybe you can included and fork JOTCache too and integrate it? 

Check it out its very good and will not be updated say the developer there http://www.jotcomponents.net/forum/5-jotcache-extension/1768-will-there-be-a-jotcache-for-joomla-4-version 

"Because of personal limitations no future version of JotCache is developed/tested for Joomla 3.10/4.0 "

**Comment by tbela99** [comment]
Hi and thanks :)

that is a lot of work and I do not plan to do a such thing. This extension does not have the same purpose as JOTCache.
