### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach() in /plugins/system/gzip/helper.php

### ISSUE THREAD

**Issue by panta7** [tbela99/gzip#12]
Hello, I'm using this plugin. My error_log_php file is increasing with an infinite rows like this:
PHP Warning:  Invalid argument supplied for foreach() in /public_html/plugins/system/gzip/helper.php
Any ideas, please?

Im running:
- Joomla 3.9.0
- Mysql 5.6.41
- Php 7.2.11

**Comment by tbela99** [comment]
Can you provide the line number please?

**Comment by tbela99** [comment]
The line number should be in the error message you are seeing

**Comment by panta7** [comment]
828
836
1901
1909

**Comment by tbela99** [comment]
thank you

**Comment by tbela99** [comment]
It should be fixed in this branch https://github.com/tbela99/gzip/tree/file_not_found
