### ISSUE TITLE
Joomla crash after enabling GZIP 2.9.1

### ISSUE THREAD

**Issue by cbahiana** [tbela99/gzip#121]
Hi Thierry

First of all, thank you for this project, it's gonna be awesome!

I installed a fresh Joomla 3.9.24 to test the GZIP plugin. It's hosted by Siteground at https://pwa.sd.eti.br

I installed the plugin, enabled the Service Worker and saved/closed it still disabled. When I enabled it I got these error messages:

Warning: require(/home/customer/www/pwa.sd.eti.br/public_html/plugins/system/gzip/vendor/composer/platform_check.php): failed to open stream: No such file or directory in /home/customer/www/pwa.sd.eti.br/public_html/plugins/system/gzip/vendor/composer/autoload_real.php on line 25

Fatal error: require(): Failed opening required '/home/customer/www/pwa.sd.eti.br/public_html/plugins/system/gzip/vendor/composer/platform_check.php' (include_path='.:/usr/local/php73/pear') in /home/customer/www/pwa.sd.eti.br/public_html/plugins/system/gzip/vendor/composer/autoload_real.php on line 25

I will disable the plugin to regain access to the admin.

**Comment by tbela99** [comment]
Thanks for reporting that. I have fixed it and published a new release. sorry for any inconvenience
