### ISSUE TITLE
Enabling OneSignal push throws error

### ISSUE THREAD

**Issue by cbahiana** [tbela99/gzip#125]
The file actually is not there yet.

Warning: file_get_contents(/home/customer/www/pwa.sd.eti.br/public_html/plugins/system/gzip/worker/dist/onesignal.min.js): failed to open stream: No such file or directory in /home/customer/www/pwa.sd.eti.br/public_html/plugins/system/gzip/gzip.php on line 197

**Comment by tbela99** [comment]
thanks for reporting. I will fix it soon.
Remember that extensions such as ublock will prevent you to load the onesignal Sdk. I will suggest you use another solution for push notifications.
I wanted to implement an alternative solution for push notifications but I don't think I will
