### ISSUE TITLE
Question about this plugin

### ISSUE THREAD

**Issue by Yovelshoval** [tbela99/gzip#128]
Can it work for shopify?
it wont cause for issues ?

I will love to talk a little more with someone about this plugin

ty

**Comment by tbela99** [comment]
Hi,

It is meant to work with Joomla. It can probably ported to shopify with a little bit of work

**Comment by Yovelshoval** [comment]
By the way im not sure what should i do to publish post here but i hope to get an answer if possible

So i guess you heard it since you are a DEV or coder etc that shopify limit the API now ,im not a coder or .... i just want to find a way to have just one checkout page in shopify i even tried to search for **API ALTERNATIVES** but didnt find something that will be able to make it work i saw something like **WEBHOOK , SDK** but i think they wont help there is a chance you know on something which will give me the option to use secure integration which will be alternative for the **API LIMITATION** in shopify so finally i will be able to make one checkout page without any issue etc?

ty

**Comment by tbela99** [comment]
this is not the place to talk about shopify api
