### ISSUE TITLE
serviceworker in offline mode

### ISSUE THREAD

**Issue by lechoslaw** [tbela99/gzip#130]
Hi
I'm setting:
"Enable Offline Page" = Yes
"Offline Method" = GET
"Prefered Offline Page" = HTML
"Offline HTML Page" = ...
"Cache Urls": 
/
/?utm_source=web_app_manifest

When I am online the whole site and service worker works fine, but when I am offline I get the error: "worker .... js: 1 Uncaught (in promise) TypeError: Failed to fetch" and the page is unreachable

**Comment by tbela99** [comment]
please check this https://tbela99.github.io/gzip/#/./service-worker?id=cache-urls
