### ISSUE TITLE
Warning: A non-numeric value encountered in /gzip/helpers/CSS.php on line 662

### ISSUE THREAD

**Issue by cbahiana** [tbela99/gzip#133]
Line 662

`$rule->setValue('(min-width: '.(array_shift($keys) + 1).'px)');`
	
So $keys might be the culprit. I introduced 

`echo '<pre>';
	print_r ($keys);
	echo  '</pre>';`
	
right after $keys = array_keys($set); and it shows
    [0] => 
    [1] => 320
    [2] => 768
    [3] => 1024

**Comment by tbela99** [comment]
we might want to apply array_filter to $keys before

**Comment by cbahiana** [comment]
Changing (array_shift($keys) + 1) to (array_shift($keys)) solves it

**Comment by tbela99** [comment]
that is not the point, I want to add 1 to the value

320 -> 321
768 -> 769
1024 -> 1025

**Comment by cbahiana** [comment]
I understand what you mean, but removing that "+ 1" actually only allows array_shift to work.

What was 
    [0] => 
    [1] => 320
    [2] => 768
    [3] => 1024

Becomes
    [0] => 320
    [1] => 768
    [2] => 1024

**Comment by cbahiana** [comment]
Unless you want
[0] => 1
[1] => 321
[2] => 769
[3] => 1025

**Comment by cbahiana** [comment]
Ok, there's more to it. 

I began experimenting with other templates and extensions. In this particular case the source of that first empty image is a module called BGMax. For some reason GZIP isn't able to fetch the image, a 404 error is thrown in the console for it. As it cannot fetch the image, it also can't grab it's size, so the the corresponding $key value is empty.

**Comment by tbela99** [comment]
you should create a separate issue for that. and As I said I need the value + 1 to build a media query. min-width: 320px is not the same as min-width:321px
