### ISSUE TITLE
al habilitar plugin gzip da error 404 

### ISSUE THREAD

**Issue by EmerIglesias** [tbela99/gzip#136]
Después de instalar el plugin Gzip 2.9.3 la web da error 404, y solo consigo solucionarlo deshabilitando el pluging. Qué problema puede haber?

**Comment by tbela99** [comment]
debe agregar un archivo .htaccess a la raíz de su sitio web y habilitar la reescritura de URL en la configuración de Joomla.
puede crear un archivo .htaccess cambiando el nombre del archivo htaccess.txt a .htaccess. se encuentra en la carpeta raíz de su sitio web.
perdonar errores de traducción automática

**Comment by EmerIglesias** [comment]
tengo archivo .htaccess. Cómo habilito la reescritura?

**Comment by tbela99** [comment]
Conéctese a la administración de su sitio Joomla y modifique esta opción allí.
Si está utilizando el servidor web apache, también debe activar el módulo mod_rewrite
