### ISSUE TITLE
Anything else needed to make Subresource Integrity Checksum work

### ISSUE THREAD

**Issue by louisjansen** [tbela99/gzip#137]
Hi there,

I installed and enable the GZIP plugin. Disabled most of its features to check if the thing that most interests me works on its own. That is the "Subresource Integrity Checksum" feature. I did set it to SHA256. But I don't see any 'signature' appearing in the source code with .js and/or .css files.

I couldn't find any additional info in the documentation. What steps do I need to take to enable this feature?

Kind regards,

Louis

**Comment by tbela99** [comment]
It looks like it requires this setting enabled https://tbela99.github.io/gzip/#/./http?id=cache-file
I might address that in the future

**Comment by tbela99** [comment]
fixed
