### ISSUE TITLE
0 Argument 1 passed to TBela\CSS\RuleList::setChildren() must be of the type array

### ISSUE THREAD

**Issue by aminweb2** [tbela99/gzip#147]
0 Argument 1 passed to TBela\CSS\RuleList::setChildren() must be of the type array, null given, called in /plugins/system/gzip/vendor/tbela99/css/src/TBela/CSS/Element.php on line 60 

https://github.com/tbela99/gzip/blob/10cdc2c02f32a6901f3b7a3c472e24c93daca9cb/vendor/tbela99/css/src/TBela/CSS/Element.php#L60

how solve this problem?

**Comment by tbela99** [comment]
I am working on it

**Comment by aminweb2** [comment]
> 
> 
> I am working on it

Thank you @tbela99

**Comment by tbela99** [comment]
can you try this branch and let me know if it works?
https://github.com/tbela99/gzip/tree/joomla4_compat

thanks

**Comment by aminweb2** [comment]
> 
> 
> can you try this branch and let me know if it works?
> https://github.com/tbela99/gzip/tree/joomla4_compat
> 
> thanks

I teste on Joomla 3.10.1 
error: 0 Argument 1 passed to TBela\CSS\Element\RuleList::setChildren() must be of the type array, null given, called in plugins/system/gzip/vendor/tbela99/css/src/TBela/CSS/Element.php on line 58 

This problem occurs when I enable the " Process CSS" option.

**Comment by tbela99** [comment]
can you provide the css file involved?
Thanks

**Comment by tbela99** [comment]
and the php version you are using as well please

**Comment by aminweb2** [comment]
> 
> 
> and the php version you are using as well please

7.3.29



> 
> 
> can you provide the css file involved?
> Thanks

I do not know what you mean

**Comment by tbela99** [comment]
I mean you provide the css file that triggers this error

**Comment by tbela99** [comment]
can you test this branch again and let me know if your issue is addressed?
https://github.com/tbela99/gzip/tree/joomla4_compat

thanks

**Comment by tbela99** [comment]
I will reopen if you still have an issue
