### ISSUE TITLE
icon formats

### ISSUE THREAD

**Issue by bossies** [tbela99/gzip#15]
First - thank you very much for this plugin, i am still testing but it seems great.

I need help with some settings - first, what name/type/size must the icons be for the pwa. I do not seem to get it to work on my phone and it just takes a default icon.

thanks

**Comment by tbela99** [comment]
Hello, the file dimensions depends on the browser. You can use this website [https://appimagegenerator-pre.azurewebsites.net/](https://appimagegenerator-pre.azurewebsites.net/) to automatically generate images for your target platform.

You put those images in a folder and you specify this folder in the plugin settings. The browser / platform will pick the right image from the manifest file

**Comment by tbela99** [comment]
sorry the link has changed to https://www.pwabuilder.com
