### ISSUE TITLE
";" character appeared at the bottom of the page

### ISSUE THREAD

**Issue by ggt-81** [tbela99/gzip#152]
If I disable de plugin it dissapear:

![character](https://user-images.githubusercontent.com/85747972/138991601-13cb0603-1e84-49bb-b3e6-efc6587dc631.png)

**Comment by ggt-81** [comment]
@tbela99 is there any way to contact you privately?

**Comment by tbela99** [comment]
you can email me at bnanga@gmail.com

**Comment by ggt-81** [comment]
Hi, please visit 

![image](https://user-images.githubusercontent.com/85747972/142729848-b225d56c-c43f-4de7-940a-1440c00715f9.png)

So you can see it on the bottom of the page.

If i disable GZIP the ; dissapear. 

Thanks for your help.

**Comment by tbela99** [comment]
I will check why and come back to you.

**Comment by tbela99** [comment]
can you send me the url of the page? I am not able to see that error.
You can delete the message after you submit it. I will still receive the notification.

Thanks

**Comment by tbela99** [comment]
that bug seems to be caused by the cookie banner javascript. It is hard to say exactly which javascript is injecting the ';' character

**Comment by tbela99** [comment]
it seems you have solved the issue? can't see it anymore

**Comment by ggt-81** [comment]
Thanks for your indications and quick response. I will close de issue now.
