### ISSUE TITLE
onesignal setup

### ISSUE THREAD

**Issue by bossies** [tbela99/gzip#17]
i have enabled the onesignal setup in the plugin and added ap id and api key ( no test user )

when i open the website, i do see a bell but nothing happens when i click on it

when i go to pwabuilder.com all is fine except Service Worker has a push registration

Could you assist me with this one please.

Thanks for all your trouble so far

**Comment by bossies** [comment]
you can have a look at www.bossies.co.za - if i look at the console there is errors that i do not understand 

thanks

**Comment by tbela99** [comment]
The error is coming from oneSignal. I would suggest you use something else because adblockers kind of block it. It will not event load if someone uses adblockers
