### ISSUE TITLE
Release 3.1.1 is broken, missing docs folder in zip-file

### ISSUE THREAD

**Issue by Orgoth** [tbela99/gzip#170]
try to install 3.1.1 in j4 -> JInstaller: :Install: Die Datei „[ROOT][TMP]/install_62cfc3242de32/gzip-3.1.1/docs“ existiert nicht.

Tested with webinstaller and manual upload

Install of 3.1.zip works without any problems.

After I added the docs folder from 3.1 to the 3.1.1 zip, the installation worked again.
Please pack the 3.1.1.zip again with docs directory.

**Comment by tbela99** [comment]
Fixed. thanks for reporting
