### ISSUE TITLE
Syntax error in helper.php

### ISSUE THREAD

**Issue by esedic** [tbela99/gzip#26]
After installing and enabling plugin I get: Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in xxx/plugins/system/gzip/helper.php on line 2616

Joomla 3.9.6, PHP 5.6.40

**Comment by tbela99** [comment]
php 5 is no longer supported but since Joomla still [supports it](https://downloads.joomla.org/technical-requirements) I will provide a fix in the next version.

In the meantime you can replace that line 

	                                (clone $image)->resizeAndCrop($mq[$k], null, $method)->save($img);
with this


	                                $cloneImg= clone $image;
	                               $cloneImg->resizeAndCrop($mq[$k], null, $method)->save($img);

**Comment by tbela99** [comment]
It should be fixed now
