### ISSUE TITLE
Joomla 2.5.11 capability

### ISSUE THREAD

**Issue by kamenWeb** [tbela99/gzip#33]
Can I use your extension ( Gzip ) on older versions of Joomla 2.5.11 for example? And if I can do I have to  make any changes?

**Comment by tbela99** [comment]
unfortunately, I have not tested against Joomla 2.5 so I can't tell if it will break or not. Hopefully there might just be few minor changes to perform.

**Comment by tbela99** [comment]
I will not backport this project to Joomla 2.5. Anyway that should not be hard to do. 
Feel free to do it.
