### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by tbela99** [tbela99/gzip#79]

**Comment by ssnobben** [comment]
Pls update your links on JED https://extensions.joomla.org/extension/core-enhancements/performance/gzip/ for Demo doesnt work ie https://ilepatmos.net/ and Documentation ie https://tbela99.github.io/gzip/Docs/dist/ doesnt work. 

Cheers!

**Comment by tbela99** [comment]
Thank you for the report. I updated the documentation link but I removed the demo link. I will need to setup a demo site anytime in the future

**Comment by ssnobben** [comment]
Thats great!  

I got this error playing with the settings and first trial.

Warning: file_get_contents(/site/plugins/system/gzip/helpers/../loader.min.js"): failed to open stream: No such file or directory in /site/plugins/system/gzip/helpers/HTML.php on line 33

**Comment by tbela99** [comment]
Thank you for your report. I will look into that soon

**Comment by tbela99** [comment]
The file is in the repository and it is specified in the xml. I am not sure why you have that error. Are you using a Linux system?

**Comment by tbela99** [comment]
Does the file exist in your plugin root folder?

**Comment by ssnobben** [comment]
I have this on a live site and can not laborate to much about it so maybe I will test it later when its more tested and also stable. I will later test it on another site and see how it works!

Cheers!

**Comment by tbela99** [comment]
I will take a look a that probably today or tomorrow.

**Comment by tbela99** [comment]
there is an extra quote at the end of the filename _n.js")_. I am fixing that soon

**Comment by tbela99** [comment]
I created bug #81 and fixed the issue.
