### ISSUE TITLE
[Bug] No Umlaut-Support in Filenames when HTTP Cache is enabled

### ISSUE THREAD

**Issue by FaySmash** [tbela99/gzip#86]
If a file contains an Umlaut (ä, ö, ü, ß) and the HTTP Cache is turned on, it can't be displayed (404)

![bug](https://user-images.githubusercontent.com/30392780/73215063-a8e6a400-4153-11ea-93a1-9bc056db5617.JPG)

**Comment by tbela99** [comment]
fixed
