### ISSUE TITLE
Incompatible with EasySocial 3.2.5

### ISSUE THREAD

**Issue by ssnobben** [tbela99/gzip#87]
Hi 

I tried to get gzip to work with EasySocial 3.2.5 J 3.9.15 no other optimisation plgs but even with disable all settings it doesnt work with EasySocial 3.2.5 and thats a pity bcs you would like to test this plg though it had a lot of interesting opmimisation settings for Joomla that could be nice if it could work. Any suggestions or have you tested it with other components than just a standard install of Joomla?

I have tested some other plgs like Lite Speed Cache that my hosting support https://www.litespeedtech.com/products/cache-plugins/joomla-acceleration and Expire headers, HTTP/2 Push    https://www.richeyweb.com/component/ars/repository/expires-headers/expires-headers-2-0/plg_expiresheaders-2-0.zip?format=zip and Javascript sync&defer https://www.daycounts.com/shop/plugins/javascript-async-defer and Server cache https://www.web-expert.gr/en/joomla-extensions/item/127-nginx-server-cache-joomla

So I dont know which combination you should use and I would like to have one solution that is compatible and can be used as one optimisation tool for Joomla  :)

Cheers!

**Comment by tbela99** [comment]
The features you mention are built into the plugin. I will take a look at your issue whenever I can.

The plugin should not interfere with your other Joomla components.

**Comment by tbela99** [comment]
The exxtension you mentioned is only available as a paid download. Unfortunately I cannot test it. My guess is that there require you to load some scripts from their servers. If you enable _fetch remote javascript files_ options then their script will trigger an error. In that case you can add those scripts to the [ignore javascript files](https://tbela99.github.io/gzip/#/./javascript?id=ignore-javascript) section

**Comment by ssnobben** [comment]
Ok I see you closed this and add tag wonfix so then I know gzip doesnt work with EasySocial 3.2.5. But all these Joomla plg and links I sent you here are all free dl updated plgs that I use and works with EasySocial and Joomla 3.9.15

Cheers!

if you still interested I can help you with EasySocial

**Comment by tbela99** [comment]
I will happily fix your issue if you can provide more details about that incompatibility (log file for example). for now there is nothing I can do since that extension is not freely available.

Feel free to reopen this issue later.

Cheers,
