### ISSUE TITLE
"Convert to Webp" doesn't work on <style="background-image:[...]"> Tags

### ISSUE THREAD

**Issue by FaySmash** [tbela99/gzip#93]
When "Convert to Webp" under the "Image" Tab is enabled, it only affects `<img src="[...]">` Tags, not on `<style="background-image:[...]">` .
Please use my csn-alpha instance to debug this, Images in the "Banner" are not processed.

**Comment by tbela99** [comment]
I will fix this as part of #67 . I am working on [this project](https://github.com/tbela99/css) that will hopefully replace the current css parser

**Comment by FaySmash** [comment]
Ah, glad to hear. Btw, Happy Easter! 🐣

**Comment by tbela99** [comment]
thank you, same to you
