### ISSUE TITLE
Error in Console when "Instant Page Preloading" is enabled

### ISSUE THREAD

**Issue by FaySmash** [tbela99/gzip#94]
When the following Settings are enabled

![settings](https://user-images.githubusercontent.com/30392780/78930751-e8f7ca80-7aa4-11ea-9e6f-45e0b9e5167d.JPG)

this error appears in the Console

![error](https://user-images.githubusercontent.com/30392780/78930589-a930e300-7aa4-11ea-92a6-38b6c5711b0a.JPG)

**Comment by tbela99** [comment]
fixed
