### ISSUE TITLE
Problems with "Responsive Images" Setting

### ISSUE THREAD

**Issue by FaySmash** [tbela99/gzip#95]
Responsive Images acts differently when the source Image has different resolutions.

I have inserted the same image twice but once with 1200x300px and again with 3780x945px. The smaller image is displayed correctly when the screen has a with of >320px while the larger image is cropped to only show the upper left corner:
![bug](https://user-images.githubusercontent.com/30392780/78997521-08473400-7b47-11ea-811d-278d90a9fcd8.JPG)

When the width is less than 320px, both images are displayed incorrectly:
![bug2](https://user-images.githubusercontent.com/30392780/78997631-388ed280-7b47-11ea-89b9-f44dd8cd9096.JPG)

please use my csn-alpha instance for debugging

**Comment by tbela99** [comment]
Did you try to change the crop settings to for example face detection? It has an incidence on the cropped area

**Comment by FaySmash** [comment]
yes I tried everyone of the settings. Please play around on csn-alpha for yourself, it's hard to explain what effects those settings had.

**Comment by tbela99** [comment]
image cropping has customizable settings. which one did you use?

![image](https://user-images.githubusercontent.com/58517/93716144-fe851c00-fb3b-11ea-9724-f22cd2ebc461.png)

**Comment by tbela99** [comment]
sorry dumb question. I already asked you about that :)

**Comment by tbela99** [comment]
I noticed you where using very large inline images even with the mobile apps. It would have been easier to optimize them if you used css classes. 
I created this issue to try to fix that problem #116
