### ISSUE TITLE
"Ignore Javacript Files" prevent the given scripts from loading

### ISSUE THREAD

**Issue by FaySmash** [tbela99/gzip#96]
It seems that the "Ignore Javacript Files" and "Remove Javacript Files" do the same and prevent the given scripts from loading.

Before:
![before](https://user-images.githubusercontent.com/30392780/79001555-f2d60800-7b4e-11ea-8aab-65ac18ee7bc8.JPG)

Settings:
![settings](https://user-images.githubusercontent.com/30392780/79001568-f79abc00-7b4e-11ea-98ff-eb6a20337b54.JPG)

After:
![after](https://user-images.githubusercontent.com/30392780/79001586-008b8d80-7b4f-11ea-86c7-8e78fa2e5d09.JPG)

**Comment by tbela99** [comment]
I cannot reproduce that issue

![image](https://user-images.githubusercontent.com/58517/80920726-c2455080-8d3f-11ea-9046-ad933c1e1241.png)

![image](https://user-images.githubusercontent.com/58517/80920754-da1cd480-8d3f-11ea-8311-3ce07e27e404.png)

Feel free to reopen this issue if I missed something

**Comment by FaySmash** [comment]
I added those two lines inside "Ignore Javascript Files" on my test instance you can play around with:
```
/media/jdbuilder/js/jdb.min.js
jdb.min.js
```
The first line has no affect at all, the second line produces the Bug described in the OP an removes the Script completely.

**Comment by tbela99** [comment]
Can you verify with the version on the dev branch? I have tested again and I do not see the problem

**Comment by tbela99** [comment]
sorry ignore my comment

**Comment by tbela99** [comment]
Fixed.

Thank you
