### ISSUE TITLE
HTML minifying removes the protocol of URLs

### ISSUE THREAD

**Issue by FaySmash** [tbela99/gzip#98]
When HTML minifying is enabled, e.g. `https://` will be shortened end to `//`.

Check csn-alpha for an example, //example.com should be https://example.com

**Comment by tbela99** [comment]
this behavior is expected. It will default to the page protocol which is https in that case

**Comment by FaySmash** [comment]
I see. For future reference: //www.paulirish.com/2010/the-protocol-relative-url/
But please consider putting such information inside the wiki, because at this point HTML minification alters not only the source code but also the rendered website.

**Comment by tbela99** [comment]
the rendering is not affected at all

**Comment by tbela99** [comment]
the protocol is only removed when it matches the page protocol.

- if you use https, links that use http will not be changed
- if you use http, links using https will not be change

the browser will use the same protocol as the page for links with relative protocol

**Comment by FaySmash** [comment]
> the rendering is not affected at all

It is. Because http and https are not only removed after the `href=` ant `title=` attribute but also inside the `<a>` tag.

Before:
```
<a title="https://example.com.info/" href="https://example.com/">https://example.com/</a>
```

After:
```
<a title="//example.com.info/" href="//example.com/">//example.com/</a>
```

Expected:
```
<a title="//example.com.info/" href="//example.com/">https://example.com/</a>
```

**Comment by tbela99** [comment]
fixed here https://github.com/tbela99/gzip/pull/90/commits/99b484e431201574bbda4af8165cd694511bea9f#diff-8c77cad49c97240e29b1895107971bca

Thank you!
